In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB 

In [4]:
hava = ['bulutlu','yagmurlu','günesli','yagmurlu','günesli','yagmurlu','bulutlu','yagmurlu','bulutlu','bulutlu','bulutlu','yagmurlu','günesli'] 

In [5]:
sıcaklık = ['ılık','soguk','sıcak','soguk','ılık','soguk','ılık','sıcak','soguk','soguk','sıcak','soguk','ılık']

In [6]:
oynama = ['evet','hayır','hayır','evet','hayır','evet','evet','hayır','hayır','evet','evet','evet','hayır']

In [7]:
#creating labelEncoder
le = preprocessing.LabelEncoder()
hava_encoder = le.fit_transform(hava)


In [8]:
hava_encoder

array([0, 2, 1, 2, 1, 2, 0, 2, 0, 0, 0, 2, 1])

In [9]:
sıcaklık_encoder = le.fit_transform(sıcaklık)

In [10]:
sıcaklık_encoder

array([2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 1, 0, 2])

In [11]:
oynama_encoder = le.fit_transform(oynama)

In [12]:
oynama_encoder

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [13]:
özellikler = zip(hava_encoder,sıcaklık_encoder)
özellikler =list(özellikler)
print(özellikler)

[(0, 2), (2, 0), (1, 1), (2, 0), (1, 2), (2, 0), (0, 2), (2, 1), (0, 0), (0, 0), (0, 1), (2, 0), (1, 2)]


In [14]:
model = GaussianNB()

In [15]:
model.fit(özellikler,oynama_encoder)

GaussianNB()

In [16]:
tahmin = model.predict([[1,1]])

In [17]:
print(tahmin)

[1]
